

node('container') {
    
    stage("get kerberos ticket") {
        sh "pwd"
        sh "ls"
        sh "klist -a"
        sh "kinit -k -t /jenkins/agent/.ssh/mlamouri.keytab"
        sh "klist -a"
    }
}
