
stage("run on master") {
    sh "pwd"
    sh "ls"
    sh "cp /var/lib/jenkins/,ssh/mlamouri.keytab ."
}

node('container') {
    stage("Copy A File") {


        copy(
            srcFile: "kerberos.keytab",
            dstFile: "kerberos.keytab"
        )
    }
}
